apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: prd
  labels:
    app: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: us-east1-docker.pkg.dev/bardsync-467801/client/client-prd:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: client-service
  namespace: prd
spec:
  selector:
    app: client
  ports:
    - port: 80
      targetPort: 3000
  type: ClusterIP
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: client-route
  namespace: prd
spec:
  parentRefs:
    - name: gke-gateway
      namespace: ingress
  # hostnames:
  #   - bardsync.com
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: client-service
          port: 80
