apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-auth
  namespace: prd
  labels:
    app: service-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-auth
  template:
    metadata:
      labels:
        app: service-auth
    spec:
      containers:
        - name: service-auth
          image: us-east1-docker.pkg.dev/bardsync-467801/service-auth/service-auth-prd:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: service-auth-service
  namespace: prd
spec:
  selector:
    app: service-auth
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
