apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-auth
  namespace: prd
  labels:
    app: service-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-auth
  template:
    metadata:
      labels:
        app: service-auth
    spec:
      containers:
        - name: service-auth
          image: us-east1-docker.pkg.dev/bardsync-467801/service-auth/service-auth-prd:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: service-auth-service
  namespace: prd
spec:
  selector:
    app: service-auth
  ports:
    - port: 80
      targetPort: 3000
  type: ClusterIP
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: service-auth-route
  namespace: prd
spec:
  parentRefs:
    - name: gke-gateway
      namespace: ingress
  # hostnames:
  #   - bardsync.com
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /api/auth/
      backendRefs:
        - name: service-auth-service
          port: 80
